spring:
  application:
    name: DocumentService
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: test_jpa
    password: 123

    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    liquibase: DEBUG
document:
  batch: 1000