spring:
  application:
    name: DocumentService

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: test_jpa
    password: 123

    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

document:
  batch: 1000